LightPride/DrinkMaster-FrontEnd

- src/main.jsx
- src/redux/auth/auth.reducer.js
- src/redux/drinks/drinks.reducer.js
- src/redux/filters/filters.reducer.js
- src/redux/store.js
підключила стор) все працює, на міті обговоримо за персіст, в яких файлах він необхідний. Персіст зараз тільки на аутинтефікації.
> redux store

- src/components/PageTitle/PageTitle.jsx
- src/components/PageTitle/PageTitle.styled.jsx
Зробив загальний компонент для заголовків сторінок
> Make PageTitle component

- src/App.jsx
- src/components/PageTitle/PageTitle.jsx
- src/components/PageTitle/PageTitle.styled.jsx
- src/main.jsx
- src/pages/AddDrinkPage/AddDrinkPage.jsx
- src/pages/AddDrinkPage/AddDrinkPage.styled.jsx
- src/pages/DrinkPage/DrinkPage.jsx
- src/pages/DrinkPage/DrinkPage.styled.jsx
- src/pages/DrinksPage/DrinksPage.jsx
- src/pages/DrinksPage/DrinksPage.styled.jsx
- src/pages/ErrorPage/ErrorPage.jsx
- src/pages/ErrorPage/ErrorPage.styled.jsx
- src/pages/HomePage/HomePage.jsx
- src/pages/HomePage/HomePage.styled.jsx
- src/pages/SigninPage/SigninPage.jsx
- src/pages/SigninPage/SigninPage.styled.jsx
- src/pages/SignupPage/SignupPage.styled.jsx
Reverts LightPride/DrinkMaster-FrontEnd#11
> Revert "clean project"

- src/pages/FavoriteDrinksPage/FavoriteDrinksPage.jsx
- src/pages/MyDrinksPage/MyDrinksPage.jsx
по відеозв'язку з тім лідом вирішуємо проблему з деплоєм
> fix imports

- src/components/DrinksItem/DrinksItem.jsx
- src/components/DrinksItem/DrinksItem.styled.jsx
- src/components/PageTitle/PageTitle.styled.jsx
- src/pages/MyDrinksPage/MyDrinksPage.styled.jsx
Зробив розмітку для карточки напою
> Drinks item component

- src/components/FollowUs/FollowUs.styled.jsx
- src/components/Layout/Header/Header.jsx
- src/components/Layout/Header/Header.styled.jsx
- src/components/Logo/Logo.jsx
- src/components/Logo/Logo.styled.jsx
- src/components/Navigation/Navigation.jsx
- src/components/Navigation/Navigation.styled.jsx
Сделал черновой хедр на десктоп для тестирования.
> Filatov feater/header

- src/components/DrinksItem/DrinksItem.jsx
- src/components/DrinksItem/DrinksItem.styled.jsx
- src/components/SeeMoreBtn/SeeMoreBtn.jsx
- src/components/SeeMoreBtn/SeeMoreBtn.styled.jsx
- src/pages/MyDrinksPage/MyDrinksPage.jsx
Додав спільну кнопку See more, додав іконку і стилі, додав картинку заглушку для карток. В цілому верстку завершив
> DrinksItem

- src/App.jsx
- src/pages/ErrorPage/ErrorPage.jsx
- src/pages/ErrorPage/ErrorPage.styled.js
- src/pages/ErrorPage/Glass.jsx
> error test

- src/components/AuthComponents/SignInForm.jsx
- src/components/AuthComponents/SignUpForm.jsx
- src/components/AuthComponents/Styled.js
- src/components/Layout/WelcomeLayout/Styled.js
- src/components/Layout/WelcomeLayout/WelcomeLayout.jsx
- src/schemas/authSchemas.js
Винесла схеми) затести як тобі тепер сторінки входу)
> welcome container

- src/components/DrinksItem/DrinksItem.jsx
- src/components/DrinksList/DrinksList.jsx
- src/components/DrinksList/DrinksList.styled.jsx
- src/pages/FavoriteDrinksPage/FavoriteDrinksPage.jsx
- src/pages/MyDrinksPage/MyDrinksPage.jsx
Додав спільний компонент дрінкі ліст, прописав логіку для дрінкс ітем
> Drinks list

- src/components/Layout/Gradient/Gradient.jsx
- src/components/Layout/Header/BurgerMenu/BurgerMenu.jsx
- src/components/Layout/Header/BurgerMenu/BurgerMenu.styled.jsx
- src/index.css
Добавил компонент Gradient и исправил скрол меню на разрешениях менее 1440
> Adds Gradient component and fixes

- src/redux/drinks/drinks.operations.js
- src/redux/drinks/drinks.reducer.js
Корегування Drink Redux
1) drinks.operations.js
Переписав запити через instance, додав token до заголовку.
Потім, коли будуть прописані (робить інша людина) auth.selectors.js - будемо брати токен з redux store.
2) drinks.reducers.js
Змінив початковий стан drink для головноі сторінки на порожній масив (раніше був порожній обєкт).
> Drink Redux AlexL fixed

- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/redux/drinks/drinks.operations.js
- src/redux/filters/filters.operations.js
- src/redux/filters/filters.reducer.js
- src/redux/filters/filters.selectors.js
Створені файли Filter Redux (1-а версія): 
1) filters.operations.js
2) filters.reducer.js
3) filters.selectors.js
> Filter_Redux AlexL

- src/components/Drinks/Drinks.jsx
- src/components/DrinksSearch/DrinksSearch.styled.jsx
- src/components/DrinksSearch/Select.styled.jsx
- src/pages/DrinksPage/DrinksPage.jsx
Покищо переробив рендеринг карток з АПІ
+
виправив стилі про які сьогодні говорили.
> Drinks search siryi

- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/pages/DrinkPage/DrinkPage.jsx
- src/redux/drinks/drinks.reducer.js
- Виправлено файл drink.reducer.js
- до файлу DrinkPageHero.jsx додана заглушка на випадок відсутності фото з back-end
- до файлу DrinkPage.jsx додана логіка (частина) запиту та отримання інформаціі з back-end
> Drink_Page Logic AlexL

- src/components/AddDrinkForm/AddDrinkForm.jsx
- src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
- src/components/AddDrinkForm/DrinkIngredientsFields/DrinkIngredientsFields.jsx
- src/components/AddDrinkForm/RecipePreparation/RecipePreparation.jsx
- src/pages/AddDrinkPage/AddDrinkPage.jsx
> Add drink page 2

- src/components/DrinksList/DrinksList.styled.jsx
- src/components/NotFoundDrinks/NotFoundDrinks.jsx
- src/components/NotFoundDrinks/NotFoundDrinks.styled.jsx
- src/pages/MyDrinksPage/MyDrinksPage.jsx
- src/pages/MyDrinksPage/MyDrinksPage.styled.jsx
Допилив сторінку з власними дрінками, поправив верстку, додав компонент для рендеру сторінки, якщо нема власних дрінків
> MyDrinksPage

- src/components/AddDrinkForm/AddDrinkForm.jsx
- src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
- src/components/AddDrinkForm/DrinkIngredientsFields/DrinkIngredientsFields.jsx
фільтрація можливості додавання алкогольних інгрідієнтів до напою в залежності від  того який чекбокс обраний. чекбокс "алкогол" блокуватиметься якщо в юзері буде інформація що він неповнолітній.
> add filters ingredients for noAdults users.

- src/components/Drinks/DrinksItem.jsx
- src/components/DrinksSearch/DrinksSearch.jsx
- src/pages/DrinksPage/DrinksPage.jsx
додав пошук по імені коктейлю
та завантаження списку селектів з АПІ
> Drinks search siryi2

- src/components/DrinkIngredientItem/DrinkIngredientItem.jsx
- src/components/DrinkIngredientList/DrinkIngredientsList.jsx
- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/pages/DrinkPage/DrinkPage.jsx
- src/redux/drinks/drinks.operations.js
- src/redux/filters/filters.operations.js
1. Внесені зміни до redux (імпортовано instance з auth.operations до drink та filter operations)
2. Додана логіка до компонентів DrinkIngredientItem, DrinkIngredientList, DrinkPageHero
> Drink_Page Logic Alex L ver2

- src/components/AuthComponents/SignInForm.jsx
- src/components/Layout/Header/BurgerMenu/BurgerMenu.styled.jsx
- src/components/Layout/Header/UserLogoPopup/UserLogoPopup.jsx
- src/components/Layout/SharedLayout/SharedLayout.jsx
- src/redux/auth/auth.operations.js
- src/redux/auth/auth.reducer.js
- src/redux/auth/auth.selectors.js
- src/schemas/authSchemas.js
Витягла меседж для інпутів з беку) зробила фон для мобільного меню)))
> Validation

- src/components/DrinkIngredientItem/DrinkIngredientItem.jsx
- src/components/DrinkIngredientList/DrinkIngredientsList.jsx
- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/redux/drinks/drinks.operations.js
- src/redux/drinks/drinks.reducer.js
1. Додана логіка до компонентів DrinkIngredientlist, DrinkIngredientItem, DrinkPageHero та сторінки DrinkPage. Зараз працює все, крім логіки додавання / видалення з Favorite, тому що end-point Favorite ще не працює. Тому не має можливості перевірити.
2. Ввнесені корективи до drink.operations відповідно до інформаціі зі swagger. Також відповідно зкорегований файл drink.reducer.
> Drink Page Logic AlexL 3rd version 

- src/components/DrinksSearch/DrinksSearch.jsx
- src/components/DrinksSearch/Select.styled.jsx
- src/pages/DrinksPage/DrinksPage.jsx
Привіт!
Додав сортування по категоріям та індігрієнтам
> added sorting by categories and ingredients

- src/components/AddDrinkForm/AddDrinkForm.jsx
- src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
- src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.styled.jsx
- src/components/AddDrinkForm/DrinkIngredientsFields/DrinkIngredientsFields.jsx
- src/components/AddDrinkForm/DrinkIngredientsFields/DrinkIngredientsFields.styled.jsx
- src/pages/AddDrinkPage/AddDrinkPage.jsx
- src/redux/drinks/drinks.operations.js
> Add dring page sidlicki

- src/components/Layout/Header/LogOutModal/LogOutModal.jsx
- src/components/Layout/Header/LogOutModal/LogOutModal.styled.jsx
- src/components/Layout/Header/UserLogo/UserLogo.jsx
Добавляет закрытия компонента userPopup по клику вне его окна. Исправляет ошибки стилей кнопки cancel в logout окне
> fixes closing logic

- src/redux/drinks/drinks.reducer.js
фікс редусера шоб не кидало еррор, бо некорректно записувало пейлоад в стейт
> фікс редусера

- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/components/DrinksItem/DrinksItem.jsx
- src/hooks/useDrink.js
- src/pages/MyDrinksPage/MyDrinksPage.jsx
- src/redux/drinks/drinks.operations.js
- src/redux/drinks/drinks.reducer.js
- src/redux/drinks/drinks.selectors.js
> My drinks page kaidanovskyi

- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/pages/DrinkPage/DrinkPage.jsx
- src/redux/drinks/drinks.operations.js
- src/redux/drinks/drinks.reducer.js
renews working Favorites.
додав коректне відображення кнопки Add to Favorites при першому завантаженні.
> Drink page Logic AlexL fixed 5th version 

- src/components/Layout/Header/UserLogo/UserLogo.jsx
- src/redux/auth/auth.reducer.js
ВНИМАНИЕ!!! Внес изменения в auth.reducer.js. !!! Исправил отображение имени пользователя.
> adds fix UserName

- src/components/DrinksItem/DrinksItem.styled.jsx
- src/pages/FavoriteDrinksPage/FavoriteDrinksPage.jsx
- src/pages/MyDrinksPage/MyDrinksPage.jsx
Відмальовується все добре, з видаленням якісь трабли, з чатом гпт сиділи кілька годин, пробували різне, не допомагає. Треба спитати у менторки, де копати
> MyDrinks and Favorite pages

- src/components/DrinksItem/DrinksItem.jsx
- src/pages/DrinksPage/DrinksPage.jsx
легенький фікс коду кирила шоб корректно видаляло зі сторінок фейворіт і май дрінкс
проблема залишається тільки при видалені з останнім коктейлем з майдрінкс. фейворіт працює корректно.
> fix sidlicki 2

- src/components/Layout/Header/Skeleton/SkeletonAuth.jsx
- src/components/Layout/Header/UserInfoModal/UserInfoModal.jsx
- src/components/Layout/Header/UserInfoModal/UserInfoModal.styled.jsx
- src/components/Layout/Header/UserLogo/UserLogo.jsx
- src/components/Layout/Header/UserLogo/UserLogo.styled.jsx
- src/components/Layout/Header/UserLogoPopup/UserLogoPopup.jsx
- src/images/addPhoto.svg
- src/redux/user/userOperations.js
- src/schemas/userProfileSchemas.js
Добавил форму добавления редактирования фото и имени.
> Adds userInfoModal

- src/redux/drinks/drinks.operations.js
додав Notiflix повідомлення про додавання та видалення з favorite та own. Це зроблено в drink.operations, щоб кожному не було потреби робити це на своій сторінці. Зараз повідомлення виводиться у верхньому правому куті. Якщо це не буде потрібно, можна просто не додавати до проєкту ))
> Notiflix message

- src/App.jsx
- src/components/Layout/Footer/Info/Info.styled.jsx
- src/components/Layout/Footer/NavFooter/NavFooter.styled.jsx
- src/redux/API/axios.js
- src/redux/auth/auth.operations.js
- src/redux/auth/auth.reducer.js
- src/redux/drinks/drinks.operations.js
- src/redux/filters/filters.operations.js
- src/redux/user/userOperations.js
Moved axios instance, added axios interceptors, fixed token error and styled footer links
> Changed Axios/Auth

- src/components/DrinkPageHero/DrinkPageHero.jsx
- src/components/DrinksItem/DrinksItem.jsx
- src/components/DrinksSearch/DrinksSearch.jsx
- src/components/Paginator/Paginator.jsx
- src/components/Paginator/Paginator.styled.jsx
- src/pages/DrinksPage/DrinksPage.jsx
- src/pages/FavoriteDrinksPage/FavoriteDrinksPage.jsx
- src/pages/MyDrinksPage/MyDrinksPage.jsx
- src/redux/drinks/drinks.operations.js
- src/redux/drinks/drinks.reducer.js
- src/redux/drinks/drinks.selectors.js
Доробив Paginator (2-а версія)
- змінив drink.operations, тому що там потрібно було додати параметри page та size для реалізаціі пагінаціі на 3-х сторінках
- змінив файли сторінок MyDrinkPage, FavoriteDrinkPage
- трохи змінив свою сторінку DrinkPage, тому що змінилися запити
- змінив стилі Paginator, щоб він по ширині відповідав макету
- зробив декілька відповідних до усього вказаного вишче
> Paginator AlexL 2nd version

- src/components/Layout/Header/UserInfoModal/UserInfoModal.jsx
- src/redux/auth/auth.reducer.js
Исправляет ошибки формы отображение аватарки и имени. Работает без перезагрузки страницы.
> fixes the logic of the form
